# Generated by Django 3.2.8 on 2022-01-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javob',
            name='matn',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='savol',
            name='matn',
            field=models.CharField(max_length=500),
        ),
    ]
